
export const CUSRO = ['PRIMER_CURSO', 'SEGUNDO_CURSO', 'TERCER_CURSO', 'CUARTO_CURSO', 'QUINTO_CURSO'] as const
export type curso = typeof CUSRO[number]

export const SEMESTRE = ['PRIMER_SEMESTRE', 'SEGUNDO_SEMESTRE', 'TERCER_SEMESTRE', 'CUARTO_SEMESTRE','QUINTO_SEMESTRE', 'SEXTO_SEMESTRE', 'SEPTIMO_SEMESTRE', 'OCTAVO_SEMESTRE','NOVENO_SEMESTRE', 'DECIMO_SEMESTRE'] as const
export type semestre = typeof SEMESTRE[number]

// Etiquetas legibles para mostrar en el <select> sin tocar el valor que viaja a la API
export const ETIQUETAS_CURSO: Record<curso, string> = {
    PRIMER_CURSO: 'PRIMER_CURSO',
    SEGUNDO_CURSO: 'SEGUNDO_CURSO',
    TERCER_CURSO: 'TERCER_CURSO',
    CUARTO_CURSO: 'CUARTO_CURSO',
    QUINTO_CURSO: 'QUINTO_CURSO'
}

export const ETIQUETAS_SEMESTRE: Record<semestre, string> = {
    PRIMER_SEMESTRE: 'PRIMER_SEMESTRE',
    SEGUNDO_SEMESTRE: 'SEGUNDO_SEMESTRE',
    TERCER_SEMESTRE: 'TERCER_SEMESTRE', 
    CUARTO_SEMESTRE: 'CUARTO_SEMESTRE',
    QUINTO_SEMESTRE: 'QUINTO_SEMESTRE',
    SEXTO_SEMESTRE: 'SEXTO_SEMESTRE',
    SEPTIMO_SEMESTRE: 'SEPTIMO_SEMESTRE',
    OCTAVO_SEMESTRE: 'OCTAVO_SEMESTRE',
    NOVENO_SEMESTRE: 'NOVENO_SEMESTRE',
    DECIMO_SEMESTRE: 'DECIMO_SEMESTRE'
}